pipeline:
  release:
    image: plugins/docker
    settings:
      repo: "madnificent/${CI_REPO_NAME}"
      tags: "${CI_COMMIT_TAG##v}"
    secrets: [ docker_username, docker_password ]
when:
  event: tag
  tag: v*
